Homework 01
rogerosha/ma_course_homework pull request #1
Opened 2020-11-09 23:20 UTC by rogerosha

2020-11-09 23:22 UTC, rogerosha commented
Hello :)

2020-11-10 00:22 UTC, XX-NF-XX commented
По **JS** замечаний нет, с основной логикой всё в порядке!

Небольшие замечания по заданию:
- Модуль `taks2` должен возвращать не саму функцию, а результат выполнения этой функции. Поэтому `goods.json` подключается в `task2` напрямую чтобы там же в `task2` его использовать как параметр. После этого в `app.js` вызов `task2` будет без параметров.
`module.exports = findMostExpensiveGood(goods);`
- В `index.js` импортируемые таски должны называться `task1`, `task2`, `task3`. Переименовывать нужно только в `app.js` и только `task1` и `task2`. Это не значит что так нужно делать всегда, просто такое вот условие в задании.

Замечания по структуре и пакетам:
- Весь код проекта должен быть в папке `src` (все js файлы и все папки которые содержат только js файлы).
- В корневом каталоге должны быть только файлы настроек и другие папки (`package.json`, `package-lock.json`, `src`, `node_modules`).
- В `package.json` должны быть подключены `eslint` и `prettier`. Нужно установить эти пакеты. Они помогут с форматированием кода.
- Файл `index.js` служит основным файлом для папки (индексом). Обычно в нём собирают пакет для экспорта (всё что есть в текущей папке), поэтому `index.js` домашнего задания должен быть внутри папки `tasks`, т.к. он собирает все таски в один объект.

2020-11-10 12:57 UTC, rogerosha commented
Исправила все, что Вы сказали

2020-11-10 20:24 UTC, XX-NF-XX requested changes
Уже совсем близко, всё почти готово.
Ещё пара мелочей и работа сдана.

2020-11-10 20:24 UTC, XX-NF-XX commented on package.json
> +  },
Любой проект Node.js можно запустить с помощью комманды `npm start`.
Когда запускают эту комманду то выполняется скрипт `"start"` который, например исполняет комманду `node ./src/app.js`. Таким образом запускается весь проект.
Сейчас проект не запускается, т.к. нет секции `"start"` в `package.json`

2020-11-10 20:24 UTC, XX-NF-XX commented on src/app.js
> +boot(goods, "type", "socks")
А как же форматирование в этом файле?
И путь к `goods.json` немного нужно исправить.

2020-11-11 14:19 UTC, XX-NF-XX approved these changes
Ура! Всё работает!

2020-11-11 14:20 UTC, merged